src/main/java/com/pivovarit/collectors/ParallelCollectionCollector.java, src/main/java/com/pivovarit/collectors/ParallelCollectors.java, src/test/java/com/pivovarit/collectors/ParallelCollectionCollectorTest.java
Related issue: https://github.com/pivovarit/parallel-collectors/issues/4
=> Implement a generic parallel collector

src/main/java/com/pivovarit/collectors/ParallelCollectors.java, src/test/java/com/pivovarit/collectors/ParallelCollectorsTest.java
Related issue: https://github.com/pivovarit/parallel-collectors/issues/4
=> Add toCollection() collector

pom.xml, src/test/java/com/pivovarit/collectors/ParallelCollectorsTest.java
Related issue: https://github.com/pivovarit/parallel-collectors/issues/15
=> Apply property-based testing

src/main/java/com/pivovarit/collectors/ParallelCollectors.java
Related issue: https://github.com/pivovarit/parallel-collectors/issues/9
=> Add more documentation

src/main/java/com/pivovarit/collectors/ParallelCollectors.java
Related issue: https://github.com/pivovarit/parallel-collectors/issues/9
=> Add ParallelCollectors JavaDoc

src/main/java/com/pivovarit/collectors/ParallelCollectors.java
=> Sanitize input params

src/test/java/com/pivovarit/collectors/TimeUtils.java, src/test/java/com/pivovarit/collectors/parallel/ParallelismTest.java
=> Refactor ParallelismTest

src/main/java/com/pivovarit/collectors/ThrottledParallelCollector.java
=> Handle RejectedExecutionException

src/main/java/com/pivovarit/collectors/ParallelCollector.java, src/main/java/com/pivovarit/collectors/ThrottledParallelCollector.java
=> Release Semaphore when interrupted

src/main/java/com/pivovarit/collectors/ParallelCollectors.java
=> Complete JavaDocs

src/main/java/com/pivovarit/collectors/ParallelCollector.java, src/main/java/com/pivovarit/collectors/ThrottledParallelCollector.java, src/test/java/com/pivovarit/collectors/BasicTest.java, src/test/java/com/pivovarit/collectors/TimeUtils.java, src/test/java/com/pivovarit/collectors/parallel/ParallelismTest.java
=> Add more tests

src/main/java/com/pivovarit/collectors/AbstractParallelCollector.java, src/main/java/com/pivovarit/collectors/ParallelCollector.java, src/main/java/com/pivovarit/collectors/ParallelCollectors.java, src/main/java/com/pivovarit/collectors/ThrottledParallelCollector.java, src/main/java/com/pivovarit/collectors/UnboundedParallelCollector.java, src/test/java/com/pivovarit/collectors/BasicTest.java, src/test/java/com/pivovarit/collectors/parallel/ParallelismTest.java
=> AbstractParallelCollector

src/main/java/com/pivovarit/collectors/ThrottledParallelCollector.java
=> RequireNonNull future from a queue

src/main/java/com/pivovarit/collectors/ThrottledParallelCollector.java, src/test/java/com/pivovarit/collectors/parallel/ParallelismTest.java
=> Release permits on exception and rethrow

src/main/java/com/pivovarit/collectors/ThrottledParallelCollector.java
=> Refactor ThrottledParallelCollector

src/main/java/com/pivovarit/collectors/Main.java, src/main/java/com/pivovarit/collectors/ThreadFactoryNameDecorator.java
=> Improve thread-factory implementation

src/test/java/com/pivovarit/collectors/BasicTest.java, src/test/java/com/pivovarit/collectors/MappingTest.java
=> Fine-tune tests

pom.xml, src/main/java/com/pivovarit/collectors/ParallelCollectors.java
=> Additional documentation

README.md
=> Redo examples

src/main/java/com/pivovarit/collectors/AbstractParallelCollector.java, src/main/java/com/pivovarit/collectors/ThrottledParallelCollector.java
=> Remove Autocloseable

README.md
=> Quote SM directly

README.md
=> Update README.md after release

src/main/java/com/pivovarit/collectors/ParallelCollectors.java
=> Improve documentation

README.md
=> Add Philosophy section to README

src/main/java/com/pivovarit/collectors/ParallelCollectors.java
=> Add @return descriptions to JavaDoc

src/main/java/com/pivovarit/collectors/AbstractParallelCollector.java, src/main/java/com/pivovarit/collectors/ThrottlingParallelCollector.java, src/main/java/com/pivovarit/collectors/UnboundedParallelCollector.java
=> collection -> collectionFactory

src/main/java/com/pivovarit/collectors/ThrottlingParallelCollector.java
=> Refactor ThreadFactory and make ThrottlingParallelCollector Autocloseable

src/main/java/com/pivovarit/collectors/ParallelCollectors.java
=> Add information about lack of ordering guarantees

src/main/java/com/pivovarit/collectors/ThrottlingParallelCollector.java
=> Shutdown dispatcher in finally block

src/main/java/com/pivovarit/collectors/ParallelCollectors.java
=> Fill missing params

src/main/java/com/pivovarit/collectors/ThrottlingParallelCollector.java
=> Rename fields of ThrottlingParallelCollector

src/main/java/com/pivovarit/collectors/ThrottlingParallelCollector.java
=> Use Queue and not ConcurrentLinkedQueue

src/main/java/com/pivovarit/collectors/ThrottlingParallelCollector.java, src/test/java/com/pivovarit/collectors/parallel/ExceptionPropagationTest.java, src/test/java/com/pivovarit/collectors/parallel/RejectedExecutionHandlingTest.java
=> Handle exception propagation

src/main/java/com/pivovarit/collectors/ThrottlingParallelCollector.java
=> Spin-wait for the next future

src/main/java/com/pivovarit/collectors/ThrottlingParallelCollector.java, src/test/java/com/pivovarit/collectors/SmokeTests.java, src/test/java/com/pivovarit/collectors/parallel/RejectedExecutionHandlingTest.java
=> Start dispatcher's thread in finisher instead of constructor

src/main/java/com/pivovarit/collectors/ThrottlingParallelCollector.java
=> Optimize the dispatcher by not iterating more than working queue size

src/main/java/com/pivovarit/collectors/ThrottlingParallelCollector.java
=> Optimize the finisher further

src/main/java/com/pivovarit/collectors/ThrottlingParallelCollector.java, src/test/java/com/pivovarit/collectors/parallel/RejectedExecutionHandlingTest.java
=> Refactor tests for higher reproducibility

src/main/java/com/pivovarit/collectors/ParallelCollectors.java, src/test/java/com/pivovarit/collectors/ExceptionPropagationTest.java, src/test/java/com/pivovarit/collectors/ExecutorAwareTest.java, src/test/java/com/pivovarit/collectors/NonblockingCollectTest.java, src/test/java/com/pivovarit/collectors/ParallelProcessingDurationTest.java, src/test/java/com/pivovarit/collectors/ParallelismThrottlingTest.java, src/test/java/com/pivovarit/collectors/RejectedExecutionHandlingTest.java, src/test/java/com/pivovarit/collectors/UnboundedCollectorsTest.java
=> Reorganize tests

src/main/java/com/pivovarit/collectors/AbstractParallelCollector.java, src/main/java/com/pivovarit/collectors/ParallelCollectors.java, src/main/java/com/pivovarit/collectors/UnboundedParallelCollector.java
=> Reorganize hierarchy

src/main/java/com/pivovarit/collectors/AbstractParallelCollector.java
=> Externalize queues

src/main/java/com/pivovarit/collectors/ThrottlingParallelCollector.java, src/test/java/com/pivovarit/collectors/ConsistencyTest.java, src/test/java/com/pivovarit/collectors/infrastructure/ExecutorAwareTest.java
=> Reproduce and fix deadlock when can't add task to queue

src/main/java/com/pivovarit/collectors/ThrottlingParallelCollector.java, src/main/java/com/pivovarit/collectors/UnboundedParallelCollector.java, src/test/java/com/pivovarit/collectors/ConsistencyTest.java
=> Improve unbounded collector

src/test/java/com/pivovarit/collectors/ConsistencyTest.java
=> Improve ConsistencyTest

src/main/java/com/pivovarit/collectors/ParallelCollectors.java
=> Improve Javadocs

README.md
=> CompletableFuture usage documentation improvements

src/test/java/com/pivovarit/collectors/parallelToCollection/ToCollectionExceptionShortCircuitTest.java, src/test/java/com/pivovarit/collectors/parallelToList/ToListExceptionShortCircuitTest.java, src/test/java/com/pivovarit/collectors/parallelToSet/ToSetExceptionShortCircuitTest.java
=> Improve short-circuiting test assertions

src/main/java/com/pivovarit/collectors/AbstractParallelCollector.java, src/main/java/com/pivovarit/collectors/ThrottlingParallelCollector.java, src/test/java/com/pivovarit/collectors/ConsistencyTest.java, src/test/java/com/pivovarit/collectors/parallelToCollection/ToCollectionExceptionShortCircuitTest.java, src/test/java/com/pivovarit/collectors/parallelToList/ToListExceptionShortCircuitTest.java, src/test/java/com/pivovarit/collectors/parallelToSet/ToSetExceptionShortCircuitTest.java
=> Simplify ThrottlingParallelCollector

README.md
=> Expand "Good Practices" section in README.md

.github/ISSUE_TEMPLATE/question.md
=> Create question.md issue template

src/test/java/com/pivovarit/collectors/FunctionalTests.java, src/test/java/com/pivovarit/collectors/MappingCollectorFunctionalTests.java, src/test/java/com/pivovarit/collectors/ThrottlingParallelCollectorConsistencyTest.java, src/test/java/com/pivovarit/collectors/parallelToCollection/ToCollectionNonBlockingFutureTest.java, src/test/java/com/pivovarit/collectors/parallelToList/ToListNonBlockingFutureTest.java, src/test/java/com/pivovarit/collectors/parallelToSet/ToSetNonBlockingFutureTest.java
=> MappingCollectorFunctionalTests

src/test/java/com/pivovarit/collectors/infrastructure/TestUtils.java, src/test/java/com/pivovarit/collectors/parallelToCollection/ToCollectionParallelismThrottlingTest.java, src/test/java/com/pivovarit/collectors/parallelToList/ToListParallelismThrottlingTest.java, src/test/java/com/pivovarit/collectors/parallelToSet/ToSetParallelismThrottlingTest.java
=> Remove duplicated code

README.md
=> Remove ambiguous Collectors from README.MD

src/test/java/com/pivovarit/collectors/CollectorFunctionalTest.java, src/test/java/com/pivovarit/collectors/infrastructure/TestUtils.java, src/test/java/com/pivovarit/collectors/parallelToCollection/ToCollectionParallelismThrottlingBDDTest.java, src/test/java/com/pivovarit/collectors/parallelToList/ToListParallelismThrottlingBDDTest.java
=> Simplify tests

src/test/java/com/pivovarit/collectors/CollectorFunctionalTest.java, src/test/java/com/pivovarit/collectors/MappingCollectorFunctionalTest.java
=> Reproduce slow-producer issue in tests

src/main/java/com/pivovarit/collectors/Dispatcher.java, src/main/java/com/pivovarit/collectors/ThrottlingParallelCollector.java, src/main/java/com/pivovarit/collectors/UnboundedParallelCollector.java
=> Dispatcher Refactor

src/main/java/com/pivovarit/collectors/AbstractParallelCollector.java
=> Remove redundant type boundaries

src/main/java/com/pivovarit/collectors/AbstractAsyncCollector.java, src/main/java/com/pivovarit/collectors/AsyncMapParallelCollector.java, src/main/java/com/pivovarit/collectors/AsyncOrderedParallelCollector.java, src/main/java/com/pivovarit/collectors/AsyncParallelCollector.java, src/main/java/com/pivovarit/collectors/AsyncParallelMapCollector.java, src/main/java/com/pivovarit/collectors/Dispatcher.java, src/main/java/com/pivovarit/collectors/ParallelCollectors.java, src/test/java/com/pivovarit/collectors/AsyncMapCollectorFunctionalTest.java
https://github.com/pivovarit/parallel-collectors/issues/8
=> ParallelCollectors#parallelToMap

src/test/java/com/pivovarit/collectors/parallelToStream/ToStreamParallelismThrottlingBDDTest.java, src/test/java/com/pivovarit/collectors/parallelToStream/ToStreamParallelismThrottlingTest.java
=> Add additional tests

src/main/java/com/pivovarit/collectors/AsyncOrderedParallelStreamCollector.java, src/main/java/com/pivovarit/collectors/ParallelCollectors.java, src/test/java/com/pivovarit/collectors/AsyncStreamCollectorFunctionalTest.java, src/test/java/com/pivovarit/collectors/parallelToStreamOrdered/ToStreamParallelismThrottlingBDDTest.java, src/test/java/com/pivovarit/collectors/parallelToStreamOrdered/ToStreamParallelismThrottlingTest.java
Related issue: https://github.com/pivovarit/parallel-collectors/issues/6
=> Add parallelToStreamOrdered

src/main/java/com/pivovarit/collectors/Dispatcher.java, src/test/java/com/pivovarit/collectors/AsyncMapCollectorFunctionalTest.java, src/test/java/com/pivovarit/collectors/AsyncMappingCollectorFunctionalTest.java, src/test/java/com/pivovarit/collectors/AsyncStreamCollectorFunctionalTest.java, src/test/java/com/pivovarit/collectors/parallel/ParallelBDDTest.java
=> Decrease default parallelism

src/main/java/com/pivovarit/collectors/AsyncParallelCollector.java, src/main/java/com/pivovarit/collectors/Dispatcher.java
Signal completion when dispatcher completes
=> Add proper completion signalling

src/main/java/com/pivovarit/collectors/CompletionOrderSpliterator.java
Reverts pivovarit/parallel-collectors#293
=> Revert "Map-based CompletionOrderSpliterator"

src/main/java/com/pivovarit/collectors/Dispatcher.java
Replace concurrent queue with a classic list
=> Replace concurrent queue with a classic list

src/main/java/com/pivovarit/collectors/Dispatcher.java
Reverts pivovarit/parallel-collectors#298
=> Revert "Replace concurrent queue with a classic list"

src/main/java/com/pivovarit/collectors/AsyncParallelCollector.java, src/main/java/com/pivovarit/collectors/Dispatcher.java
=> Simplify internal implementation

src/test/java/com/pivovarit/collectors/ArchitectureTest.java
=> Improve ArchUnit tests

src/main/java/com/pivovarit/collectors/Dispatcher.java
=> Enable CF cancellation of multiple backing tasks

src/main/java/com/pivovarit/collectors/AsyncParallelCollector.java
=> Simplify AsyncParallelCollector

src/main/java/com/pivovarit/collectors/BatchingIterator.java, src/main/java/com/pivovarit/collectors/ParallelCollectors.java
=> Remove redundant collectors

src/main/java/com/pivovarit/collectors/AsyncParallelCollector.java, src/main/java/com/pivovarit/collectors/BatchingStream.java, src/main/java/com/pivovarit/collectors/ParallelStreamCollector.java
=> Extract repetitive default batch number

CHANGELOG.MD
=> ADD 2.1.0 changelog

README.md
=> Add notes in documentation

src/main/java/com/pivovarit/collectors/AsyncParallelCollector.java, src/main/java/com/pivovarit/collectors/BatchingStream.java, src/main/java/com/pivovarit/collectors/ParallelStreamCollector.java, src/test/java/com/pivovarit/collectors/BatchingStreamTest.java
=> Remove unused code

pom.xml, src/main/java/com/pivovarit/collectors/AsyncParallelCollector.java, src/main/java/com/pivovarit/collectors/FutureCollectors.java, src/main/java/com/pivovarit/collectors/ParallelCollectors.java, src/test/java/com/pivovarit/collectors/FutureCollectorsTest.java
https://github.com/pivovarit/parallel-collectors/issues/428
=> Add ParallelCollectors#toFuture

src/test/java/com/pivovarit/collectors/ArchitectureTest.java
=> Refactor ArchitectureTest

pom.xml
=> Exclude architecture tests from mutation testing pipeline

.github/workflows/build.yml
=> Build against JDK 16 EA

src/main/java/com/pivovarit/collectors/Dispatcher.java
Back off and give it one more try before erroring
=> Retry once when provided Executor rejected

src/test/java/com/pivovarit/collectors/test/Factory.java
=> Add missing test cases
