pivovarit/parallel-collectors

pom.xml, src/main/java/com/pivovarit/collectors/ParallelCollectors.java, src/test/java/com/pivovarit/collectors/AsyncMappingCollectorFunctionalTest.java, src/test/java/com/pivovarit/collectors/infrastructure/TestUtils.java
Implement parallelToListOrdered() collectors that can be a supplied with a custom List implementation
Related issue: https://github.com/pivovarit/parallel-collectors/issues/196
=> parallelToListOrdered() collectors suppliable with custom List implementation

pom.xml, src/main/java/com/pivovarit/collectors/AsyncParallelCollector.java, src/main/java/com/pivovarit/collectors/ParallelCollectors.java, src/test/java/com/pivovarit/collectors/AsyncMappingCollectorFunctionalTest.java
https://github.com/pivovarit/parallel-collectors/issues/331
For now, just applying custom postprocessing with `r.thenApply(s -> s.collect(collector))` - to be revisited.
=> Enable application of java.util.stream.Collector instances

src/test/java/com/pivovarit/collectors/FunctionalTest.java
`FunctionalTest#shouldRespectParallelism` would always pass since parallelism was enforced by the size of the thread pool. Reverting to an unbounded one.
=> Fix shouldRespectParallelism test

src/main/java/com/pivovarit/collectors/AsyncParallelCollector.java
Relying on `BiFunction` instead of `BiConsumer` makes it possible to make the code a bit more concise.
=> Refactor AsyncParallelCollector

src/main/java/com/pivovarit/collectors/Dispatcher.java
This reverts commit 6d33f254bfa4a87f4cfa14f5fbc2a33fa31d5769 due to lack of perceivable performance improvement
=> Revert "Drop Semaphore for unbounded Dispatcher (#414)"

src/main/java/com/pivovarit/collectors/AsyncParallelCollector.java, src/main/java/com/pivovarit/collectors/ParallelCollectors.java, src/main/java/com/pivovarit/collectors/ParallelStreamCollector.java, src/test/java/com/pivovarit/collectors/Bench.java
https://github.com/pivovarit/parallel-collectors/issues/417
Before:
```
Benchmark                               (parallelism)   Mode  Cnt      Score     Error  Units
Bench.parallel_batch_collect                        1  thrpt    5  10218.766 ± 131.633  ops/s
Bench.parallel_batch_streaming_collect              1  thrpt    5  10715.432 ±  78.383  ops/s
Bench.parallel_collect                              1  thrpt    5     67.891 ±   1.357  ops/s
Bench.parallel_streaming                            1  thrpt    5     50.920 ±   1.569  ops/s
```
After:
```
Benchmark                               (parallelism)   Mode  Cnt      Score     Error  Units
Bench.parallel_batch_collect                        1  thrpt    5  32793.324 ± 898.335  ops/s
Bench.parallel_batch_streaming_collect              1 …
```
=> Optimize for parallelism of one

src/main/java/com/pivovarit/collectors/AsyncParallelCollector.java, src/main/java/com/pivovarit/collectors/ParallelCollectors.java, src/test/java/com/pivovarit/collectors/blackbox/CountingExecutor.java, src/test/java/com/pivovarit/collectors/blackbox/FunctionalTest.java
https://github.com/pivovarit/parallel-collectors/issues/461
=> Fix inconsistent behavior when parallel=1

src/main/java/com/pivovarit/collectors/ParallelCollectors.java
Since the main use-case for the library is to assist with long-running IO tasks, it's not wise to apply resolution typical for CPU-bound tasks.
This can result in surprising behaviour when running code on various machines.
----
Fixes https://github.com/pivovarit/parallel-collectors/issues/465
=> Deprecate API methods with implicit parallelism resolution

src/main/java/com/pivovarit/collectors/Dispatcher.java
There's no point in restoring the interruption flag in this case
=> Don't restore interruption flag

pom.xml, src/main/java/com/pivovarit/collectors/ParallelStreamCollector.java, src/test/java/com/pivovarit/collectors/blackbox/FunctionalTest.java
Whenever using one of the factories returning `Stream<T>`, the internal dispatcher creates an extra internal thread to orchestrate the processing.
However, this is not necessary since the calling thread could perform the same job. For now, it just blocks and waits for the results.
=> Use a calling thread when using blocking streaming instead of creating a new one

pom.xml, src/main/java/com/pivovarit/collectors/AsyncParallelCollector.java, src/main/java/com/pivovarit/collectors/ParallelStreamCollector.java, src/test/java/com/pivovarit/collectors/FunctionalTest.java
There's no point in batching when each batch would carry only a single element.
=> Avoid batching when collection size is equal to parallelism

src/main/java/com/pivovarit/collectors/AsyncParallelCollector.java, src/main/java/com/pivovarit/collectors/CompletionOrderSpliterator.java, src/main/java/com/pivovarit/collectors/CompletionStrategy.java, src/main/java/com/pivovarit/collectors/ParallelStreamCollector.java, src/test/java/com/pivovarit/collectors/ArchitectureTest.java, src/test/java/com/pivovarit/collectors/CompletionOrderSpliteratorTest.java, src/test/java/com/pivovarit/collectors/FunctionalTest.java
That allows to simplify the internal implementation.
=> Use List<> instead of Stream.Builder<> as accumulators

src/main/java/com/pivovarit/collectors/Dispatcher.java
Just in case someone tries to call `.parallel()` on a _Stream_ instance returned by parallel collectors.
=> Ensure that Dispatcher can't be started more than one time

src/main/java/com/pivovarit/collectors/Dispatcher.java
JDK21 introduced `Thread.ofPlatform()...factory()` - no need to rely on a custom implementation
=> Use native ThreadFactory creator instead of custom one

README.md, src/main/java/com/pivovarit/collectors/AsyncParallelCollector.java, src/main/java/com/pivovarit/collectors/Dispatcher.java, src/main/java/com/pivovarit/collectors/ParallelStreamCollector.java, src/test/java/com/pivovarit/collectors/CompletionOrderSpliteratorTest.java, src/test/java/com/pivovarit/collectors/FunctionalTest.java, src/test/java/com/pivovarit/collectors/FutureCollectorsTest.java, src/test/java/com/pivovarit/collectors/TestUtils.java, src/test/java/com/pivovarit/collectors/benchmark/Bench.java
Remove the internal single-thread scheduler and rely on the caller thread to submit all relevant tasks to a given thread pool. This not only simplified the solution, but also:
- helped avoid context propagation issues when execution switches between multiple threads
- made the tool more Loom-friendly since instances of `ParallelCollectors` do not create their own threads
=> Dispatcher to use caller thread instead of dedicated scheduler thread

src/main/java/com/pivovarit/collectors/AsyncParallelCollector.java, src/main/java/com/pivovarit/collectors/Dispatcher.java, src/main/java/com/pivovarit/collectors/ParallelCollectors.java, src/main/java/com/pivovarit/collectors/ParallelStreamCollector.java, src/test/java/com/pivovarit/collectors/CompletionOrderSpliteratorTest.java, src/test/java/com/pivovarit/collectors/FunctionalTest.java, src/test/java/com/pivovarit/collectors/TestUtils.java
Make executor and parallelism parameters optional and default to virtual threads when not provided.
=> Default to VirtualThreads when Executor not provided

src/main/java/com/pivovarit/collectors/Dispatcher.java, src/test/java/com/pivovarit/collectors/ExecutorValidationTest.java
Disallow `ThreadPoolExecutor.DiscardOldestPolicy` and `ThreadPoolExecutor.DiscardPolicy` since they are fundamentally unsafe and can induce permanent inconsistencies when dropping some of the tasks
=> Reject invalid Executor's RejectedExecutionHandlers

src/main/java/com/pivovarit/collectors/AsyncParallelCollector.java, src/main/java/com/pivovarit/collectors/Dispatcher.java, src/main/java/com/pivovarit/collectors/ParallelStreamCollector.java, src/test/java/com/pivovarit/collectors/ExecutorPollutionTest.java
Addresses: https://github.com/pivovarit/parallel-collectors/issues/867
=> Control max parallelism on a dedicated thread

src/main/java/com/pivovarit/collectors/Dispatcher.java
There's no need for using the builder when all we need is to simply start a `Thread`
=> Replace 'Thread.ofVirtual().start()' with 'Thread.startVirtualThread()'

src/main/java/com/pivovarit/collectors/AsyncParallelCollector.java, src/main/java/com/pivovarit/collectors/Dispatcher.java, src/main/java/com/pivovarit/collectors/ParallelCollectors.java, src/main/java/com/pivovarit/collectors/ParallelStreamCollector.java, src/test/java/com/pivovarit/collectors/FunctionalTest.java
Add new API methods that accept a custom `Executor` but allow unlimited parallelism without extra overhead:
```
Collector<...> parallel(Function<T, R> mapper, Collector<R, ?, RR> collector, Executor executor)
Collector<...> parallel(Function<T, R> mapper, Executor executor) 
Collector<...> parallelToStream(Function<T, R> mapper, Executor executor)
Collector<...> parallelToOrderedStream(Function<T, R> mapper, Executor executor)
```
resolves: https://github.com/pivovarit/parallel-collectors/issues/918
=> Add new API methods supporting custom Executors with unbounded parallelism

src/main/java/com/pivovarit/collectors/AsyncParallelCollector.java, src/test/java/com/pivovarit/collectors/FunctionalTest.java, src/test/java/com/pivovarit/collectors/test/RejectedExecutionHandlingTest.java
When it comes to handling `RejectedExecutionException`
=> Align behaviour of async colllector with other implementations

src/main/java/com/pivovarit/collectors/AsyncParallelCollector.java, src/main/java/com/pivovarit/collectors/BatchingSpliterator.java, src/main/java/com/pivovarit/collectors/ParallelCollectors.java, src/main/java/com/pivovarit/collectors/ParallelStreamCollector.java, src/test/java/com/pivovarit/collectors/TypeBoundsTest.java
Let's say we have a `Collector` accepting `Integer` elements and returning a `Stream<String>`.
This can be achieved by passing `Function<Integer, String>`, but it would be perfectly valid to pass `Function<Object, String>` as well, but it's not possible at the moment:
```java
Function<Integer, String> f1 = i -> i.toString();
Function<Object, String> f2 = i -> i.toString();
Collector<Integer, ?, CompletableFuture<Stream<String>>> e1 = parallel((Integer i) -> i.toString());
// Incompatible equality constraint: Integer and Object
Collector<Integer, ?, CompletableFuture<Stream<String>>> e2 = parallel((Object i) -> i.toString());
```
This change loosens generic type bounds to maximize variance support, making this possible.
=> Use Function<? super T, ? extends R> to maximize variance support

src/main/java/com/pivovarit/collectors/AsyncParallelCollector.java, src/test/resources/benchmarks/AsyncCollectorBenchmark.json
When a parallelism level of 1 is requested, it effectively means the Stream should be processed on a single thread. To do this efficiently, we've introduced a custom `Collector` implementation that avoids the overhead of task dispatching.
Further optimization was achieved by collecting elements directly into a `Stream.Builder`, which significantly improved performance:
```
Benchmark                         Mode     Cnt      Score       Error    Units
AsyncCollectorBenchmark.existing  thrpt    5        16990.054 ± 277.907  ops/s
AsyncCollectorBenchmark.improved  thrpt    5        32742.449 ± 227.698  ops/s
```
----
```java
private static final List<Integer> source = IntStream.iterate(0, i -> i + 1)
.limit(10_000)
.boxed().toList();
@Benchmark
public Stream<Integer> existing() {
return …
```
=> Faster async Collector

src/main/java/com/pivovarit/collectors/AsyncParallelCollector.java, src/main/java/com/pivovarit/collectors/ParallelCollectors.java, src/main/java/com/pivovarit/collectors/ParallelStreamCollector.java, src/test/java/com/pivovarit/collectors/TypeBoundsTest.java
Let's say we have a `Collector` accepting `Integer` elements and returning a `Stream<Number>`.
This can be achieved by passing `Function<Integer, Number>`, but it would be perfectly valid to pass `Function<Integer, Integer>` as well, but it's not possible at the moment:
```java
Function<Integer, Number> f1 = i -> i;
Function<Integer, Integer> f2 = i -> i;
Collector<Integer, ?, CompletableFuture<Stream<Number>>> collector = ParallelCollectors.parallel(f1, 42);
// Incompatible equality constraint: Number and Integer
Collector<Integer, ?, CompletableFuture<Stream<Number>>> collector = ParallelCollectors.parallel(f2, 42);
```
This change loosens generic type bounds to maximize variance support, making this possible.
----
related: https://github.com/pivovarit/parallel-collectors/pull/1023
=> Use Function<? super T, ? extends R> to maximize variance support (covariance)
